// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AdminLayout = "_AdminLayout";
                public readonly string _AdminMenu = "_AdminMenu";
                public readonly string _DeleteModal = "_DeleteModal";
                public readonly string _Modal = "_Modal";
                public readonly string _ModalAdminLayout = "_ModalAdminLayout";
                public readonly string _ModalMain = "_ModalMain";
                public readonly string _NotingModel = "_NotingModel";
                public readonly string _PictureAdd = "_PictureAdd";
                public readonly string _SubjectForm = "_SubjectForm";
                public readonly string _ToolsCloseModal = "_ToolsCloseModal";
                public readonly string _ToolsConfirmDelete = "_ToolsConfirmDelete";
                public readonly string _ToolsEdit = "_ToolsEdit";
                public readonly string _ToolsSetAddPicture = "_ToolsSetAddPicture";
            }
            public readonly string _AdminLayout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
            public readonly string _AdminMenu = "~/Areas/Admin/Views/Shared/_AdminMenu.cshtml";
            public readonly string _DeleteModal = "~/Areas/Admin/Views/Shared/_DeleteModal.cshtml";
            public readonly string _Modal = "~/Areas/Admin/Views/Shared/_Modal.cshtml";
            public readonly string _ModalAdminLayout = "~/Areas/Admin/Views/Shared/_ModalAdminLayout.cshtml";
            public readonly string _ModalMain = "~/Areas/Admin/Views/Shared/_ModalMain.cshtml";
            public readonly string _NotingModel = "~/Areas/Admin/Views/Shared/_NotingModel.cshtml";
            public readonly string _PictureAdd = "~/Areas/Admin/Views/Shared/_PictureAdd.cshtml";
            public readonly string _SubjectForm = "~/Areas/Admin/Views/Shared/_SubjectForm.cshtml";
            public readonly string _ToolsCloseModal = "~/Areas/Admin/Views/Shared/_ToolsCloseModal.cshtml";
            public readonly string _ToolsConfirmDelete = "~/Areas/Admin/Views/Shared/_ToolsConfirmDelete.cshtml";
            public readonly string _ToolsEdit = "~/Areas/Admin/Views/Shared/_ToolsEdit.cshtml";
            public readonly string _ToolsSetAddPicture = "~/Areas/Admin/Views/Shared/_ToolsSetAddPicture.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
