// <auto-generated />
namespace Aghsat.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_vehicle_property : IMigrationMetadata
    {
         readonly ResourceManager Resources = new ResourceManager(typeof(edit_vehicle_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201904131849545_edit_vehicle_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
