// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Aghsat.UI.Areas.Admin.Controllers
{
    public partial class PanelManagmentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PanelManagmentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PanelManagmentController Actions { get { return MVC.Admin.PanelManagment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PanelManagment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PanelManagment";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Menu = "Menu";
            public readonly string SaveUserSlide = "SaveUserSlide";
            public readonly string ManagmentSliderImages = "ManagmentSliderImages";
            public readonly string ShowImages = "ShowImages";
            public readonly string SaveImageSlide = "SaveImageSlide";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Menu = "Menu";
            public const string SaveUserSlide = "SaveUserSlide";
            public const string ManagmentSliderImages = "ManagmentSliderImages";
            public const string ShowImages = "ShowImages";
            public const string SaveImageSlide = "SaveImageSlide";
        }


        static readonly ActionParamsClass_SaveImageSlide s_params_SaveImageSlide = new ActionParamsClass_SaveImageSlide();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveImageSlide SaveImageSlideParams { get { return s_params_SaveImageSlide; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveImageSlide
        {
            public readonly string img = "img";
            public readonly string file = "file";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _SaveImageSlide = "_SaveImageSlide";
                public readonly string _ShowImages = "_ShowImages";
                public readonly string Index = "Index";
                public readonly string ManagmentSliderImages = "ManagmentSliderImages";
                public readonly string SaveUserSlide = "SaveUserSlide";
            }
            public readonly string _SaveImageSlide = "~/Areas/Admin/Views/PanelManagment/_SaveImageSlide.cshtml";
            public readonly string _ShowImages = "~/Areas/Admin/Views/PanelManagment/_ShowImages.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/PanelManagment/Index.cshtml";
            public readonly string ManagmentSliderImages = "~/Areas/Admin/Views/PanelManagment/ManagmentSliderImages.cshtml";
            public readonly string SaveUserSlide = "~/Areas/Admin/Views/PanelManagment/SaveUserSlide.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PanelManagmentController : Aghsat.UI.Areas.Admin.Controllers.PanelManagmentController
    {
        public T4MVC_PanelManagmentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MenuOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Menu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Menu);
            MenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveUserSlideOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveUserSlide()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveUserSlide);
            SaveUserSlideOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ManagmentSliderImagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManagmentSliderImages()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManagmentSliderImages);
            ManagmentSliderImagesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ShowImagesOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ShowImages()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ShowImages);
            ShowImagesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveImageSlideOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SaveImageSlide()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SaveImageSlide);
            SaveImageSlideOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveImageSlideOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Aghsat.ViewModel.Slider.Slider_Add_vm img, System.Web.HttpPostedFileBase file);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveImageSlide(Aghsat.ViewModel.Slider.Slider_Add_vm img, System.Web.HttpPostedFileBase file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveImageSlide);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "img", img);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            SaveImageSlideOverride(callInfo, img, file);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
